import React, { createContext, useReducer, useEffect } from "react";

const EmployeeContext = createContext();

const EMPLOYEES_STORAGE_KEY = "hrms_employees";

const initialState =
  JSON.parse(localStorage.getItem(EMPLOYEES_STORAGE_KEY)) || [
    {
      id: 1,
      fullName: "vijay choudhary",
      email: "vijaychoudhary@example.com",
      department: "IT",
      role: "Senior Developer",
      status: "Active",
      payrollStatus: "Approved",
      joiningDate: "2023-01-15",
      leaveStatus: "Pending",
      leaveReason: "Personal work",
      leaveCount: 3,
      leaveType: "casual",
      leaveFrom:"2025-09-17",
      leaveTo:"2025-09-19",
      payrollMonth:"2025-09",
      employees: ["vijay choudhary", "sunil choudhary", "deepak singh"],
      basic: 55000,
      allowances: 5000,
      deductions: 2000,
      attendanceRate: 97,
      averageSalary: 50000,
      departmentName: "IT",
      manager: "vijay choudhary",
    },
    {
      id: 2,
      fullName: "Tanvi shukla",
      email: "tanvishukla@example.com",
      department: "HR",
      role: "HR",
      status: "Active",
      payrollStatus: "Processed",
      joiningDate: "2022-06-10",
      leaveStatus: "Approved",
      leaveStatus: "Approved",
      leaveReason: "Family function",
      leaveCount: 2,
      leaveType: "casual",
      leaveFrom: "2025-10-16",
      leaveTo: "2025-10-17",
      employees: ["Tanvi shukla", "urvi meena"],
      basic: 47000,
      allowances: 3200,
      deductions: 1600,
      attendanceRate: 98,
      averageSalary: 46500,
      departmentName: "HR",
      manager: "Sonia Kapoor",
    },
    {
      id: 3,
      fullName: "gopal sharma",
      email: "gopalsharma@example.com",
      department: "Finance",
      role: "Charted Accountant",
      status: "Active",
      payrollStatus: "Pending",
      joiningDate: "2022-11-05",
      leaveStatus: "Pending",
      leaveReason: "Medical appointment",
      leaveCount: 1,
      leaveType: "sick",
      leaveFrom: "2025-10-22",
      leaveTo: "2025-10-22",
      employees: ["gopal sharma", "yukta mishra"],
      basic: 48000,
      allowances: 4000,
      deductions: 1800,
      attendanceRate: 94,
      averageSalary: 48000,
      departmentName: "Finance",
      manager: "Gopal Sharma",
    },
    {
      id: 4,
      fullName: "sunil choudhary",
      email: "sunilchoudhary@example.com",
      department: "IT",
      role: "Developer",
      status: "Active",
      payrollStatus: "Processed",
      joiningDate: "2023-03-12",
      leaveStatus: "Rejected",
      leaveReason: "Vacation trip request too long",
      leaveCount: 7,
      leaveType: "earned",
      leaveFrom: "2025-10-25",
      leaveTo: "2025-10-31",
      employees: ["vijay choudhary", "sunil choudhary", "deepak singh"],
      basic: 52000,
      allowances: 4500,
      deductions: 2200,
      attendanceRate: 95,
      averageSalary: 50000,
      departmentName: "IT",
      manager: "vijay choudhary",
    },
    {
      id: 5,
      fullName: "deepak singh",
      email: "deepaksingh@example.com",
      department: "Design",
      role: "Senior Designer",
      status: "Inactive",
      payrollStatus: "Pending",
      joiningDate: "2021-08-08",
      leaveStatus: "Pending",
      leaveReason: "Urgent home repair",
      leaveCount: 2,
      leaveType: "casual",
      leaveFrom: "2025-11-02",
      leaveTo: "2025-11-03",
      employees: ["deepak singh"],
      basic: 48000,
      allowances: 4000,
      deductions: 1800,
      attendanceRate: 90,
      averageSalary: 47000,
      departmentName: "Design",
      manager: "Rahul Desai",
    },
    {
      id: 6,
      fullName: "urvi meena",
      email: "urvimeena@example.com",
      department: "HR",
      role: "HR",
      status: "Active",
      payrollStatus: "Processed",
      joiningDate: "2021-12-20",
      leaveStatus: "Approved",
      leaveReason: "Festival celebration",
      leaveCount: 3,
      leaveType: "casual",
      leaveFrom: "2025-11-07",
      leaveTo: "2025-11-09",
      employees: ["Tanvi shukla", "urvi meena"],
      basic: 45000,
      allowances: 3000,
      deductions: 1500,
      attendanceRate: 97,
      averageSalary: 46000,
      departmentName: "HR",
      manager: "Sonia Kapoor",
    },
    {
      id: 7,
      fullName: "yukta mishra",
      email: "yuktamishra@example.com",
      department: "Finance",
      role: "Developer",
      status: "Active",
      payrollStatus: "Pending",
      joiningDate: "2022-02-28",
      leaveStatus: "Pending",
      leaveReason: "Out-of-town travel",
      leaveCount: 4,
      leaveType: "earned",
      leaveFrom: "2025-11-15",
      leaveTo: "2025-11-18",
      employees: ["gopal sharma", "yukta mishra"],
      basic: 47000,
      allowances: 3600,
      deductions: 1900,
      attendanceRate: 93,
      averageSalary: 48000,
      departmentName: "Finance",
      manager: "Gopal Sharma",
    },
    {
      id: 8,
      fullName: "Vikram Patel",
      email: "vikrampatel@example.com",
      department: "IT",
      role: "Senior Developer",
      status: "Active",
      payrollStatus: "Processed",
      joiningDate: "2023-05-14",
      leaveStatus: "Approved",
      leaveReason: "Personal work",
      leaveCount: 1,
      leaveType: "sick",
      leaveFrom: "2025-11-27",
      leaveTo: "2025-11-27",
      employees: ["Vikram Patel", "Sunil Choudhary", "Deepak Singh"],
      basic: 57000,
      allowances: 5100,
      deductions: 2300,
      attendanceRate: 96,
      averageSalary: 52000,
      departmentName: "IT",
      manager: "Vikram Patel",
    },
    {
      id: 9,
      fullName: "Anjali Verma",
      email: "anjaliverma@example.com",
      department: "Finance",
      role: "Finance Analyst",
      status: "Active",
      payrollStatus: "Approved",
      joiningDate: "2022-04-19",
      leaveStatus: "Approved",
      leaveReason: "Family function",
      leaveCount: 2,
      leaveType: "casual",
      leaveFrom: "2025-10-16",
      leaveTo: "2025-10-17",
      employees: ["Anjali Verma", "Gopal Sharma"],
      basic: 48000,
      allowances: 4000,
      deductions: 2000,
      attendanceRate: 94,
      averageSalary: 49000,
      departmentName: "Finance",
      manager: "Gopal Sharma",
    },
    {
      id: 10,
      fullName: "Sonia Kapoor",
      email: "soniakapoor@example.com",
      department: "HR",
      role: "Manager",
      status: "Active",
      payrollStatus: "Processed",
      joiningDate: "2021-03-01",
      leaveStatus: "Rejected",
      leaveReason: "Vacation trip request too long",
      leaveCount: 7,
      leaveType: "earned",
      leaveFrom: "2025-10-25",
      leaveTo: "2025-10-31",
      employees: ["Tanvi Shukla", "Urvi Meena"],
      basic: 49000,
      allowances: 3500,
      deductions: 1500,
      attendanceRate: 98,
      averageSalary: 48000,
      departmentName: "HR",
      manager: "Sonia Kapoor",
    },
  ];

function reducer(state, action) {
  switch (action.type) {
    case "ADD_EMPLOYEE":
      return [...state, action.payload];
    case "UPDATE_EMPLOYEE":
      return state.map((emp) =>
        emp.id === action.payload.id ? action.payload : emp
      );
    case "DELETE_EMPLOYEE":
      return state.filter((emp) => emp.id !== action.payload);
    default:
      return state;
  }
}

export function EmployeeProvider({ children }) {
  const [employees, dispatch] = useReducer(reducer, initialState);

  useEffect(() => {
    localStorage.setItem(EMPLOYEES_STORAGE_KEY, JSON.stringify(employees));
  }, [employees]);

  return (
    <EmployeeContext.Provider value={{ employees, dispatch }}>
      {children}
    </EmployeeContext.Provider>
  );
}

export default EmployeeContext;
